parameters:
#    eticom_gas.example.class: Eticom\GasBundle\Example

services:
    login_listener:
        class:     Eticom\GasBundle\Listener\LoginListener
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }