security:
    firewalls:
        #administracion:
            #pattern: ^/admin
            #anonymous: ~
            #form_login:
            #    login_path: /admin/login
            #    check_path: /admin/login_check
            #logout:
                #path: administracion_logout
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login:
                default_target_path: /inicio/
                login_path: /login
                check_path: /login_check                
            logout:
                path: usuario_logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/*, roles: [ROLE_USUARIO,ROLE_ADMIN] }

    providers:
        usuarios:
            entity: { class: Eticom\GasBundle\Entity\usuarios, property:usuario }
    encoders:
        Eticom\GasBundle\Entity\usuarios: { algorithm: sha512, iterations:10 }

